# docker compose file for playbook.rcpch.tech (for local development)

services:
  mkdocs:
    build: .
    volumes:
      - .:/app/
    ports:
      - 8001:8001
    environment:
      - ENABLE_GIT_COMMITTERS=True # Disables git committer extension in local dev
      - ENABLE_PDF_EXPORT=0 # Disables automatic PDF generation in local dev
    command: mkdocs serve --config-file mkdocs.yml
    restart: always
