# main site metadata and titles
site_name: RCPCH Incubator Playbook
site_description: Manual and Reference for the RCPCH Incubator Team
site_author: The Royal College of Paediatrics and Child Health
site_url: https://docs.epilepsy12.rcpch.ac.uk

# copyright information which is shown in the footer
copyright: Copyright &copy; 2022 Royal College of Paediatrics and Child Health (RCPCH)

# these lines configure the 'GitHub repo' widget on the top right
repo_url: https://github.com/rcpch/rcpch-incubator-playbook
repo_name: rcpch/rcpch-incubator-playbook
edit_uri: blob/live/docs

# `mkdocs serve` serves the documentation at custom port (to avoid clashing with other services we commonly run)
dev_addr: "0.0.0.0:8001"

nav:
  - Home:
    - "index.md"
    - 'about/authors.md'
    - 'about/contact.md'
  - Principles:
    - 'principles/general-principles.md'
    - 'principles/open-source.md'
    - 'principles/security.md'
    - 'principles/12fa.md'
    - 'principles/tools.md'
  - Developer's Guide:
    - 'developer/start-here.md'
    - 'developer/programming-language.md'
    - Local Development:
      - 'developer/local-dev/local-dev-env.md'
      - 'developer/local-dev/pyenv.md'
      - 'developer/local-dev/venv.md'
      - 'developer/local-dev/docker.md'
    - 'developer/python-specific/python-specifics.md'
    - Guide to Git:
      - 'developer/git/overview.md'
      - 'developer/git/walkthrough.md'
      - 'developer/git/signed-commits.md'
    - 'developer/security/ssh-keys.md'
    - 'developer/security/ubuntu-hardening.md'
    - 'developer/contributing.md'
    - 'developer/versioning.md'
    - 'developer/writing-documentation.md'
    - 'developer/deployment.md'
    - 'developer/domain-names.md'
  - Projects:
    - 'projects/repo-map.md'
    - RCPCH Census Engine: 
      - 'projects/census/about.md'
      - 'projects/census/deprivare.md'
    - Hermes-Docker: 
      - 'projects/hermes/hermes-docker.md'
  - Legal: 'legal/copyright.md'
  

# theme settings, fonts, colours
theme:
  name: material
  #custom_dir: rcpch-theme
  features:
    - content.action.edit # explicitly adds edit button (Material4MkDocs9.0) 
    - content.action.view # explicitly adds view button (Material4MkDocs9.0) 
    - navigation.expand
    - navigation.footer # explicitly adds footer prev/next (Material4MkDocs9.0)
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    # - toc.integrate

  palette:
    # Light mode only for now
    scheme: default

  font:
    text: Montserrat
    code: Roboto Mono

  logo: '_assets/_images/rcpch_logo.png'

# mkdocs plugins
plugins:
  - git-committers:
      repository: rcpch/rcpch-incubator-playbook
      branch: live
      enabled: !ENV [ENABLE_GIT_COMMITTERS, false] # makes Git Committers optional
  # - git-revision-date-localized:
  #     enable_creation_date: true
  - search
  - with-pdf:
      back_cover: false
      cover_title: RCPCH Incubator Playbook
      cover_subtitle: Complete Manual
      exclude_pages:
        - 'home/download/'
      output_path: pdf/rcpch-epilepsy12-full-documentation.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      #debug_html: true
      #show_anchors: true
      #verbose: true

# additional markdown features
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

# set extra CSS file
extra_css:
  - _assets/_stylesheets/extra.css

# footer links and variables
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rcpchtweets
    - icon: fontawesome/brands/github
      link: https://github.com/rcpch
