# main site metadata and titles
site_name: RCPCH Incubator Playbook
site_description: Manual and Reference for the RCPCH Incubator Team
site_author: The Royal College of Paediatrics and Child Health
site_url: https://docs.epilepsy12.rcpch.ac.uk

# copyright information which is shown in the footer
copyright: Copyright &copy; 2022 Royal College of Paediatrics and Child Health (RCPCH)

# these lines configure the 'GitHub repo' widget on the top right
repo_url: https://github.com/rcpch/rcpch-incubator-playbook
repo_name: rcpch/rcpch-incubator-playbook
edit_uri: blob/live/docs

# `mkdocs serve` serves the documentation at custom port (to avoid clashing with other services we commonly run)
dev_addr: "127.0.0.1:8002"

nav:
  - Home: "index.md"
  - About:
    - 'about/about.md'
    - 'about/authors.md'
    - 'about/contact.md'
    - 'about/acknowledgements.md'
  - Principles:
    - 'principles/general-principles.md'
    - 'principles/open-source.md'
    - 'principles/security.md'
    - 'principles/tools.md'
  - Developer's Guide:
    - 'developer/start-here.md'
    - 'developer/programming-language.md'
    - Local Development:
      - 'developer/local-dev/local-dev-env.md'
      - 'developer/local-dev/pyenv.md'
      - 'developer/local-dev/venv.md'
      - 'developer/local-dev/docker.md'
    - 'developer/python-specific/python-specifics.md'
    - 'developer/versioning.md'
    - 'developer/writing-documentation.md'
    - 'developer/contributing.md'
    - 'developer/deployment.md'
    - 'developer/domain-names.md'
    - 'developer/git.md'
  - Projects:
    - RCPCH Census Platform: 
      - 'projects/census/about.md'
      - 'projects/census/deprivare.md'
    - Hermes-Docker: 
      - 'projects/hermes/hermes-docker.md'
  - Legal:
    - 'legal/copyright.md'
  - Technical:
    - 'technical/security.md'
    - 'technical/data-security-protection-toolkit.md'
    - 'technical/status.md'
  - Clinical Safety:
    - 'safety/overview.md'
    - Clinical Safety File:
      - 'safety/csmf/clinical-risk-mgmt-system.md'
      - 'safety/csmf/clinical-risk-mgmt-plan.md'
      - 'safety/csmf/clinical-safety-case-report.md'
      - 'safety/csmf/hazard-log.md'
      - 'safety/csmf/third-party-tools-safety-assmt.md'
      - 'safety/csmf/license.md'
    - DTAC:
      - 'safety/dtac.md'
    - Medical Devices Registration:
      - 'safety/medical-device-reg/mhra.md'
      - 'safety/medical-device-reg/essential-req.md'
      - 'safety/medical-device-reg/doc-api.md'
      - 'safety/medical-device-reg/mdr-technical-docs.md'
    - Download: 'safety/download.md'
  

# theme settings, fonts, colours
theme:
  name: material
  #custom_dir: rcpch-theme
  features:
    - content.action.edit # explicitly adds edit button (Material4MkDocs9.0) 
    - content.action.view # explicitly adds view button (Material4MkDocs9.0) 
    - navigation.expand
    - navigation.footer # explicitly adds footer prev/next (Material4MkDocs9.0)
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    # - toc.integrate

  palette:
    # Light mode only for now
    scheme: default

  font:
    text: Montserrat
    code: Roboto Mono

  # favicon: _assets/_images/dynamic-child-favicon.png
  logo: '_assets/_images/rcpch_logo.png'

# mkdocs plugins
plugins:
  - git-committers:
      repository: rcpch/digital-growth-charts-documentation
      branch: live
      enabled: !ENV [ENABLE_GIT_COMMITTERS, false] # makes Git Committers optional
  # - git-revision-date-localized:
  #     enable_creation_date: true
  - macros
  - search
  - render_swagger

# additional markdown features
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html #insiders
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      check_paths: true
      auto_append:
        - includes/_abbreviations.md
  - pymdownx.superfences
  - toc:
      permalink: false

# set extra CSS file
extra_css:
  - _assets/_stylesheets/extra.css

# footer links and variables
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rcpchtweets
    - icon: fontawesome/brands/github
      link: https://github.com/rcpch
