# main site metadata and titles
site_name: RCPCH Incubator Playbook
site_description: Manual and Reference for the RCPCH Incubator Team
site_author: The Royal College of Paediatrics and Child Health
site_url: https://docs.epilepsy12.rcpch.ac.uk

# copyright information which is shown in the footer
copyright: Copyright &copy; 2022 Royal College of Paediatrics and Child Health (RCPCH)

# these lines configure the 'GitHub repo' widget on the top right
repo_url: https://github.com/rcpch/epilepsy12-documentation
repo_name: rcpch/epilepsy12-documentation
edit_uri: blob/live/docs

# `mkdocs serve` serves the documentation at custom port (to avoid clashing with other services we commonly run)
dev_addr: "127.0.0.1:8002"

# theme settings, fonts, colours
theme:
  name: material
  #custom_dir: rcpch-theme
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.expand
    # - toc.integrate

  palette:
    # Light mode only for now
      scheme: default

  font:
    text: Montserrat
    code: Roboto Mono

  # favicon: _assets/_images/dynamic-child-favicon.png
  logo: _assets/_images/rcpch_logo.png

# mkdocs plugins
plugins:
  - search

# additional markdown features
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true

# set extra CSS file
extra_css:
  - _assets/_stylesheets/extra.css

# footer links and variables
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rcpchtweets
    - icon: fontawesome/brands/github
      link: https://github.com/rcpch
      
