# This Action builds the Incubator site in MkDocs, and pushes it to the gh-pages branch, from where it is deployed
# GitHub pages is a backup: https://rcpch.github.io/rcpch-incubator-playbook
# Azure Static Web Sites is the main site https://incubator.rcpch.tech/

name: build-and-deploy-to-gh-pages.yml
on:
  push:
    branches:
      - live
jobs:
  build-and-deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'live'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force # Output files are force-pushed to gh-pages branch
     
  # Azure deploy disabled as it is not yet needed for this project    
  # deploy-gh-pages-branch-to-azure:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         ref: 'gh-pages' # Use the newly-built 'gh-pages' branch not the default 'live' branch
  #     - uses: Azure/static-web-apps-deploy@v1
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_BUSH_03EE83F03 }}
  #         repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
  #         action: "upload"
  #         ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
  #         # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
  #         app_location: "/" # App source code path
  #         api_location: "" # Api source code path - optional
  #         output_location: "" # Built app content directory - optional
  #         ###### End of Repository/Build Configurations ######
